include:
  - board: xiao_ble
    shield: corne_dongle
  - board: nice_nano
    shield: corne_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_SPLIT_BLE_ROLE_CENTRAL=n
  - board: nice_nano
    shield: corne_right nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_SPLIT_BLE_ROLE_CENTRAL=n
  - board: xiao_ble
    shield: settings_reset
  - board: nice_nano
    shield: settings_reset
