manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: carrefinho
      url-base: https://github.com/carrefinho
    - name: olafkrawczyk
      url-base: https://github.com/olafkrawczyk
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # Fork of carrefinho/prospector-zmk-module (bongo cat screen added there)
    - name: prospector-zmk-module
      remote: olafkrawczyk
      revision: feat/new-status-screens
  self:
    path: config
